### ISSUE TITLE
homepage - image links need more descriptive names

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#19] opened 2020-11-02 18:09 UTC
https://omeka.religiousecologies.org/s/census-1926/page/home

VOU is reading the images as only having numbers as names. The names on the images should probably reflect the title (i.e "Denominations image" or "image for Denominations) instead of "3331"

**Comment by kimisgold** [comment] 2020-11-04 21:10
Closing as a duplicate of #8.

**Closed by kimisgold** 2020-11-04 21:10 UTC
