### ISSUE TITLE
Location tab does not have usable "home" page 

### ISSUE THREAD

**Issue by lbrannan-hub** [religious-ecologies/omeka-s-theme#2] opened 2020-10-29 16:38 UTC
There is just blank text in the middle of the page when you first click the location tab. It seems counter-intuitive and lacking in some sort of way. (Using Safari on MacBook Air).
<img width="1391" alt="Screen Shot 2020-10-29 at 12 35 34 PM" src="https://user-images.githubusercontent.com/60223963/97604167-969bde00-19e3-11eb-9eb4-a0ba7ffc8d4a.png">

**Comment by lmullen** [comment] 2020-12-07 18:30
This is a duplicate of #51, so closing this one.

**Closed by lmullen** 2020-12-07 18:30 UTC
Labels: content
